version: '3.8'

services:
  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: bayt-al-kitab-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bayt-al-kitab-network

  # PHP-FPM Service
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: webdevops/php-nginx:8.2-alpine
    container_name: bayt-al-kitab-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bayt-al-kitab-network
    # Alternative: utiliser une image pré-construite si build échoue
    # image: webdevops/php-nginx:8.2-alpine

  # Database Service (SQLite for simplicity)
  db:
    image: alpine:latest
    container_name: bayt-al-kitab-db
    volumes:
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - bayt-al-kitab-network

networks:
  bayt-al-kitab-network:
    driver: bridge 