version: '3.8'

services:
  # PHP-FPM + Nginx Service (tout-en-un)
  app:
    image: webdevops/php-nginx:8.2-alpine
    container_name: bayt-al-kitab-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bayt-al-kitab-network
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
    command: >
      sh -c "
        # Permissions immédiates
        chown -R www-data:www-data /var/www &&
        chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
        
        # Créer la base de données
        mkdir -p /var/www/database &&
        touch /var/www/database/database.sqlite &&
        chown www-data:www-data /var/www/database/database.sqlite &&
        chmod 664 /var/www/database/database.sqlite &&
        
        # Installer Composer si nécessaire
        if [ ! -d /var/www/vendor ]; then
          composer install --no-dev --optimize-autoloader
        fi &&
        
        # Configuration Laravel
        if [ ! -f /var/www/.env ]; then
          cp /var/www/.env.example /var/www/.env &&
          php artisan key:generate
        fi &&
        
        # Lien de stockage
        php artisan storage:link &&
        
        # Migrations et seeders
        php artisan migrate --force &&
        php artisan db:seed --force &&
        
        # Permissions finales
        chown -R www-data:www-data /var/www &&
        chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
        
        # Démarrer les services
        /entrypoint supervisord
      "

  # Database Service (SQLite for simplicity)
  db:
    image: alpine:latest
    container_name: bayt-al-kitab-db
    volumes:
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - bayt-al-kitab-network

networks:
  bayt-al-kitab-network:
    driver: bridge 