version: '3.8'

services:
  # PHP-FPM + Nginx Service (tout-en-un)
  app:
    image: webdevops/php-nginx:8.2-alpine
    container_name: bayt-al-kitab-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/init-laravel.sh:/usr/local/bin/init-laravel.sh
    networks:
      - bayt-al-kitab-network
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
    command: >
      sh -c "
        chmod +x /usr/local/bin/init-laravel.sh &&
        /usr/local/bin/init-laravel.sh &&
        /entrypoint supervisord
      "

  # Database Service (SQLite for simplicity)
  db:
    image: alpine:latest
    container_name: bayt-al-kitab-db
    volumes:
      - ./database/database.sqlite:/var/www/database/database.sqlite
    networks:
      - bayt-al-kitab-network

networks:
  bayt-al-kitab-network:
    driver: bridge 